### ISSUE TITLE
rand/srand issue in pkg build

### ISSUE THREAD

**Issue by antagomir** [antagomir/netresponse#1]
Running inst/extras/build.sh produces the following NOTE:

File ‘netresponse/libs/netresponse.so’:
  Found ‘rand’, possibly from ‘rand’ (C)
    Object: ‘netresponse.o’
  Found ‘srand’, possibly from ‘srand’ (C)
    Object: ‘netresponse.o’

This might become a problem in the next BioC release round (not sure).

Closer inspection shows that the rand and srand are used in ICMg part of the code in
https://github.com/antagomir/netresponse/blob/master/src/netresponse.c

Found some discussion behind these links:
http://r.789695.n4.nabble.com/Building-R-package-Found-rand-possibly-from-rand-C-NOTE-when-checking-package-td4699120.html
http://stackoverflow.com/questions/26698164/building-r-package-found-rand-possibly-from-rand-c-note-when-checking

**Comment by ouzor** [comment]
No idea about this... If it's okay to wait and check whether this is a
problem with BioC, I would do that?

**Comment by antagomir** [comment]
Sure, ok.

**Comment by antagomir** [comment]
Does not seem to pose a problem any more.
